name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node 18.x
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Building Plugin
      run: npm run build

    - name: Testing Plugin
      run: ng test --browsers ChromeHeadless